import CategoryGeneratorForm from "@/components/category-generator/CategoryGeneratorForm";
import CategoryTabs from "@/components/category-generator/CategoryTabs";
import PageTitle from "@/components/PageTitle";
import { Metadata } from "next";
import Link from "next/link";
import React from "react";

export const metadata: Metadata = {
  title: "AI Auto-Category & Tag Genrator",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 h-full divide-x-2 divide-stone-800 relative">
      <div className="h-full w-full p-4 flex items-center mt-8 md:mt-0 md:justify-center flex-col">
        <PageTitle>AI Auto-Category & Tag Genrator</PageTitle>
        <CategoryGeneratorForm />
      </div>
      <div className="h-full w-full p-4 flex items-center justify-center">
        <CategoryTabs />
      </div>

      <Link
        href="/"
        className="absolute top-3 left-3 underline underline-offset-2"
      >
        Go Back
      </Link>
    </div>
  );
}
